/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.oantuti;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.IOException;

import com.mycompany.oantuti.*;

/**
 *
 * @author hhoa3267
 */
public class Login extends JFrame {

    /**
     * Creates new form Login
     */
    public Login() throws IOException
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws IOException {

        lblTitle = new JLabel(); 
        lblUsername = new JLabel();
        lblClass = new JLabel();
        txtUsername = new JTextField();
        btnClear = new JButton();
        btnLogin = new JButton();
        txtUserClass = new JTextField();
        lblBackground = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(255, 255, 255));
        setMinimumSize(new Dimension(548, 414));
        getContentPane().setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Vào Game");

        
        lblTitle.setBounds(0,0, 548, 50);
        lblTitle.setText("<html><h1 style='text-align: center; color: #ff6685'>"+"Nhập Thông Tin"+"</h1></html>");
        lblTitle.setVerticalAlignment(SwingConstants.CENTER);
        lblTitle.setHorizontalAlignment(SwingConstants.CENTER);

        this.getContentPane().add(lblTitle);

        lblUsername.setBackground(new Color(255, 255, 255));
        lblUsername.setFont(customFont); // NOI18N
        lblUsername.setForeground(new Color(255, 255, 255));
        lblUsername.setBorder(BorderFactory.createLineBorder(new Color(31, 18, 53)));
        Image userImage = ImageIO.read(getClass().getResource("images/user.png"));
        ImageIcon userIcon = new ImageIcon(userImage.getScaledInstance(35, 35, Image.SCALE_SMOOTH));
        lblUsername.setIcon(userIcon);
        lblUsername.setText("Tên của bạn");
        getContentPane().add(lblUsername);
        lblUsername.setBounds(10, 60, 200, 50);

        lblClass.setBackground(new Color(255, 255, 255));
        lblClass.setFont(customFont); // NOI18N
        lblClass.setForeground(new Color(255, 255, 255));
        Image classImage = ImageIO.read(getClass().getResource("images/class.jpg"));
        ImageIcon keyIcon = new ImageIcon(classImage.getScaledInstance(35, 35, Image.SCALE_SMOOTH));
        lblClass.setIcon(keyIcon);
        lblClass.setText("Lớp");
        lblClass.setBorder(BorderFactory.createLineBorder(new Color(31, 18, 53)));
        getContentPane().add(lblClass);
        lblClass.setBounds(10, 130, 200, 50);

        txtUsername.setFont(customFont); // NOI18N
        txtUsername.setForeground(new Color(31, 18, 53));
        txtUsername.setBorder(BorderFactory.createLineBorder(new Color(31, 18, 53)));
        getContentPane().add(txtUsername);
        txtUsername.setBounds(220, 60, 320, 50);

        btnClear.setBackground(new Color(255, 110, 108));
        btnClear.setFont(customFont); // NOI18N
        btnClear.setForeground(new Color(31, 18, 53));
        btnClear.setText("Làm Lại");
        btnClear.setMnemonic(KeyEvent.VK_L);
        btnClear.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(280, 230, 250, 70);

        btnLogin.setBackground(new Color(255, 110, 108));
        btnLogin.setFont(customFont); // NOI18N
        btnLogin.setForeground(new Color(31, 18, 53));
        btnLogin.setText("Vào");
        btnLogin.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(10, 230, 250, 70);

        txtUserClass.setFont(customFont); // NOI18N
        txtUserClass.setForeground(new Color(31, 18, 53));
        txtUserClass.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(31, 18, 53)));
        getContentPane().add(txtUserClass);
        txtUserClass.setBounds(220, 130, 320, 50);
        txtUserClass.setMargin(new Insets(5,5,5,5));

        this.getContentPane().add(lblBackground);
        Image bgImage = ImageIO.read(getClass().getResource("images/background.jpg"));
        ImageIcon bgImageIcon = new ImageIcon(bgImage.getScaledInstance(548, 414, Image.SCALE_SMOOTH));
        lblBackground.setIcon(bgImageIcon);        
        lblBackground.setBounds(0,0,548,414);

        }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtUsername.setText("");
        txtUserClass.setText("");
        txtUsername.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private boolean isNull(String val){
        return val.equals("");
    }

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(isNull(txtUsername.getText()))
            JOptionPane.showMessageDialog(this,"Vui lòng điền tên !!! ", "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(isNull(txtUserClass.getText()))
            JOptionPane.showMessageDialog(this,"Vui lòng điền lớp !!! ", "ERROR", JOptionPane.ERROR_MESSAGE);
        else{
            try {
                new OanTuTi(txtUsername.getText(), txtUserClass.getText()).setVisible(true);
                this.dispose();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                try{
                    new Login().setVisible(true);
                }catch(Exception ex){
                    ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel lblTitle;
    private JButton btnClear;
    private JButton btnLogin;
    private JLabel lblUsername;
    private JLabel lblClass;
    private JTextField txtUserClass;
    private JTextField txtUsername;
    private Font customFont = new Font("Menlo", 0, 18);
    private JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}